# BUILD STAGE

FROM node:12-alpine as builder

WORKDIR /app/

ENV NODE_ENV=dev

COPY package.json ./
COPY tsconfig.json ./
COPY yarn.lock ./
COPY nodemon.json ./
COPY .npmrc ./
COPY ./src ./src
COPY ./config ./config
RUN yarn

#Labels as per https://github.com/opencontainers/image-spec/blob/master/annotations.md

LABEL org.opencontainers.image.url="https://dev.azure.com/endeavor-digital/Technology%20Infrastructure/_git/mvp-app-service?path=%2FREADME.md"
LABEL org.opencontainers.image.source="https://dev.azure.com/endeavor-digital/Technology%20Infrastructure/_git/mvp-app-service"
LABEL org.opencontainers.image.vendor="Endeavor"
LABEL org.opencontainers.image.title="Endeavor Experiences MVP app service"

# see https://dev.azure.com/endvr-d-cdp/Endeavor%20Experiences/_git/platform-api?path=%2FREADME.md&_a=preview&anchor=keycloak-realm-config-(the-automatic-way)

# If aws-cognito, it is the id of an application created in the user pool.
# IMPORTANT: the application must be created with `Generate client secret` NOT SET
ENV AUTH_PROVIDER_CLIENT_ID=""
# if aws-cognito, the User Pool's region
ENV AUTH_PROVIDER_REGION=""
# This is the user designed to be represent the service
ENV AUTH_PROVIDER_SERVICE_USERNAME=""
ENV AUTH_PROVIDER_SERVICE_PASSWORD=""

# Accounts service URL
ENV SDK_ACCOUNTS_URL="http://accounts-service/api/accounts/v1/"
# Notifications service URL
ENV SDK_NOTIFICATIONS_URL="http://notifications-service/api/notifications/v1/notifications/"

EXPOSE 3080/tcp

ENTRYPOINT ["yarn", "start-dev"]
