# BUILD STAGE

FROM node:12-alpine as builder

WORKDIR /app/

ENV NODE_ENV=dev

COPY package.json ./
COPY tsconfig.json ./
COPY yarn.lock ./
COPY nodemon.json ./
COPY .npmrc ./
COPY ./src ./src
COPY ./config ./config
RUN yarn

#Labels as per https://github.com/opencontainers/image-spec/blob/master/annotations.md

LABEL org.opencontainers.image.url="https://dev.azure.com/endeavor-digital/Technology%20Infrastructure/_git/mvp-app-service?path=%2FREADME.md"
LABEL org.opencontainers.image.source="https://dev.azure.com/endeavor-digital/Technology%20Infrastructure/_git/mvp-app-service"
LABEL org.opencontainers.image.vendor="Endeavor"
LABEL org.opencontainers.image.title="Endeavor Experiences MVP app service"

# see https://dev.azure.com/endvr-d-cdp/Endeavor%20Experiences/_git/platform-api?path=%2FREADME.md&_a=preview&anchor=keycloak-realm-config-(the-automatic-way)

# backend auth server url
ENV KEYCLOAK_BACKEND_AUTH_SERVER_URL='http://keycloak-service:8080/auth/'
ENV KEYCLOAK_BACKEND_CLIENT='endeavor-speakers-backend'
ENV KEYCLOAK_BACKEND_CREDENTIALS_SECRET='secret'

# frontend auth server url
ENV KEYCLOAK_FRONTEND_AUTH_SERVER_URL='http://keycloak-service:8080/auth/'
ENV KEYCLOAK_FRONTEND_CLIENT='endeavor-speakers-frontend'

ENV KEYCLOAK_REALM='endeavor-speakers'

ENV SDK_AUTH_URL='http://localhost:3080/api/auth/v1/auth/'
ENV SDK_NOTIFICATIONS_URL='http://localhost:3080/api/notifications/v1/notifications/'


EXPOSE 3080/tcp

ENTRYPOINT ["yarn", "start-dev"]
